// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesteLTrace.Models.Comtext;

#nullable disable

namespace TesteLTrace.Migrations
{
    [DbContext(typeof(TesteLTraceContext))]
    partial class TesteLTraceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TesteLTrace.Models.ModelFiltro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("HighPass")
                        .HasColumnType("double");

                    b.Property<double>("LowPass")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("ModelFiltros");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HighPass = 1.0,
                            LowPass = 1.0
                        });
                });

            modelBuilder.Entity("TesteLTrace.Models.ModelGrafico", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("DadosSismico")
                        .HasColumnType("double");

                    b.Property<int>("ModelFiltroId")
                        .HasColumnType("int");

                    b.Property<double>("Tempo")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("ModelFiltroId");

                    b.ToTable("ModelGraficos");

                    b.HasData(
                        new
                        {
                            Id = 1010,
                            DadosSismico = -4.7469604000000002E-07,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 2,
                            DadosSismico = -1.3063789999999999E-06,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 3,
                            DadosSismico = 5.5409564000000002E-06,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 4,
                            DadosSismico = 3.5207419999999999E-05,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 5,
                            DadosSismico = 5.2020758E-05,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 6,
                            DadosSismico = 6.0402551999999999E-05,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 7,
                            DadosSismico = -4.3129519E-05,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 8,
                            DadosSismico = -0.0001125016,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 9,
                            DadosSismico = -0.00018260432,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 10,
                            DadosSismico = -0.00015841763999999999,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 11,
                            DadosSismico = -0.00011617896,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 12,
                            DadosSismico = -0.00013290521999999999,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 13,
                            DadosSismico = -0.00037435323000000001,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 14,
                            DadosSismico = -0.00068153446999999999,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 15,
                            DadosSismico = -0.00031832642999999998,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 16,
                            DadosSismico = 0.00046329557999999997,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 17,
                            DadosSismico = -0.00037943242999999998,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 18,
                            DadosSismico = -0.0037876899999999998,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 19,
                            DadosSismico = -0.0054747199999999998,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 20,
                            DadosSismico = 0.00042749097000000002,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 21,
                            DadosSismico = 0.01129542,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 22,
                            DadosSismico = 0.01534481,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 23,
                            DadosSismico = 0.0058036800000000003,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 24,
                            DadosSismico = -0.0085639700000000006,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 25,
                            DadosSismico = -0.01388226,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 26,
                            DadosSismico = -0.0076128599999999999,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 27,
                            DadosSismico = 0.0013743399999999999,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 28,
                            DadosSismico = 0.0059568199999999998,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 29,
                            DadosSismico = 0.0059667899999999996,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 30,
                            DadosSismico = 0.0031811999999999999,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 31,
                            DadosSismico = -0.00125056,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 41,
                            DadosSismico = -0.0046695499999999997,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 51,
                            DadosSismico = -0.0039806800000000003,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 61,
                            DadosSismico = -6.5110777000000004E-05,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 71,
                            DadosSismico = 0.00263525,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 81,
                            DadosSismico = 0.0013581699999999999,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 91,
                            DadosSismico = -0.0022255700000000001,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 101,
                            DadosSismico = -0.0041904300000000002,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 201,
                            DadosSismico = -0.0025229800000000002,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 301,
                            DadosSismico = 0.00150468,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 401,
                            DadosSismico = 0.0042796900000000001,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 501,
                            DadosSismico = 0.0034871699999999999,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 601,
                            DadosSismico = 0.00047537008999999999,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 701,
                            DadosSismico = -0.00111418,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 801,
                            DadosSismico = -0.00012526485,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 901,
                            DadosSismico = 0.00067645544000000004,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 32,
                            DadosSismico = -0.0011019300000000001,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 33,
                            DadosSismico = -0.0038094299999999999,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 34,
                            DadosSismico = -0.0042684100000000003,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 35,
                            DadosSismico = -0.00202688,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 36,
                            DadosSismico = 0.0010157,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 37,
                            DadosSismico = 0.0034266600000000002,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 38,
                            DadosSismico = 0.0045318199999999998,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 39,
                            DadosSismico = 0.0034148300000000002,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 40,
                            DadosSismico = -9.0311965000000003E-05,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 42,
                            DadosSismico = -0.0039939800000000003,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 43,
                            DadosSismico = -0.00504003,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 44,
                            DadosSismico = -0.0017662400000000001,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 45,
                            DadosSismico = 0.0033193300000000001,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 46,
                            DadosSismico = 0.0057649399999999996,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 47,
                            DadosSismico = 0.0038215599999999999,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 48,
                            DadosSismico = 0.0001423753,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 49,
                            DadosSismico = -0.00211393,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 50,
                            DadosSismico = -0.0025071899999999999,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 52,
                            DadosSismico = -0.00185713,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 53,
                            DadosSismico = -0.00013720396000000001,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 54,
                            DadosSismico = 0.0023142900000000001,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 55,
                            DadosSismico = 0.0034364500000000002,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 56,
                            DadosSismico = 0.0015027599999999999,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 57,
                            DadosSismico = -0.0021918200000000001,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 58,
                            DadosSismico = -0.0039553599999999998,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 59,
                            DadosSismico = -0.0017480799999999999,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 60,
                            DadosSismico = 0.0020869299999999999,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 62,
                            DadosSismico = 0.00311306,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 63,
                            DadosSismico = 4.1200335999999998E-05,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 65,
                            DadosSismico = -0.0037933400000000001,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 64,
                            DadosSismico = -0.0046736299999999998,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 66,
                            DadosSismico = -0.00218674,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 1,
                            DadosSismico = 0.0014880200000000001,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 67,
                            DadosSismico = 0.0041812200000000002,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 68,
                            DadosSismico = 0.0046059899999999999,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 69,
                            DadosSismico = 0.00209465,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 70,
                            DadosSismico = -0.0021980699999999999,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 72,
                            DadosSismico = -0.00469068,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 73,
                            DadosSismico = -0.0021596800000000002,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 76,
                            DadosSismico = 0.0035108100000000001,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 78,
                            DadosSismico = 0.0061200100000000004,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 79,
                            DadosSismico = 0.0031043199999999998,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 80,
                            DadosSismico = -0.00089744007000000005,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 810,
                            DadosSismico = -0.00096810102999999995,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 82,
                            DadosSismico = 0.00038296446999999998,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 83,
                            DadosSismico = -0.0023652399999999998,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 84,
                            DadosSismico = -0.0079985999999999998,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 85,
                            DadosSismico = -0.0087342099999999992,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 86,
                            DadosSismico = -0.00056528149000000005,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 87,
                            DadosSismico = 0.010557850000000001,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 88,
                            DadosSismico = 0.01466104,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 89,
                            DadosSismico = 0.0073115599999999999,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 90,
                            DadosSismico = -0.0067625699999999999,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 92,
                            DadosSismico = -0.017395770000000001,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 93,
                            DadosSismico = -0.015960559999999999,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 94,
                            DadosSismico = -0.0028647500000000001,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 95,
                            DadosSismico = 0.01101428,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 96,
                            DadosSismico = 0.01418228,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 97,
                            DadosSismico = 0.00656275,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 98,
                            DadosSismico = -0.00172098,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 99,
                            DadosSismico = -0.0034644900000000002,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 102,
                            DadosSismico = -0.00097349909000000003,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 103,
                            DadosSismico = 0.00043476541999999999,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 104,
                            DadosSismico = -0.00024356152999999999,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 106,
                            DadosSismico = -0.00087278237000000005,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 107,
                            DadosSismico = -0.00062934902999999996,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 108,
                            DadosSismico = -0.00022400485,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 109,
                            DadosSismico = -0.00018248211,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 112,
                            DadosSismico = -0.00022873518,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 113,
                            DadosSismico = -0.00019961090999999999,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 114,
                            DadosSismico = -0.00019236178,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 115,
                            DadosSismico = -0.00014879073,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 116,
                            DadosSismico = -9.5523987999999996E-05,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 117,
                            DadosSismico = -1.2213283000000001E-05,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        },
                        new
                        {
                            Id = 118,
                            DadosSismico = 1.0215716999999999E-05,
                            ModelFiltroId = 1,
                            Tempo = 4000.0
                        });
                });

            modelBuilder.Entity("TesteLTrace.Models.ModelGrafico", b =>
                {
                    b.HasOne("TesteLTrace.Models.ModelFiltro", null)
                        .WithMany("Resultados")
                        .HasForeignKey("ModelFiltroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TesteLTrace.Models.ModelFiltro", b =>
                {
                    b.Navigation("Resultados");
                });
#pragma warning restore 612, 618
        }
    }
}
